[package]
name = "shroud"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.11.0"
# asset_manager = { path = "../AssetManager" }

[features]
default = ["amethyst/metal"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
